version: '3'
services:
############
# Setup node container
############
  server: 
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
############
# Setup client container
############
  client:
    build: ./client
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    depends_on:
      - server